### ISSUE TITLE
No get_config attribute in timingsclient.perf

### ISSUE THREAD

**Issue by mstefan7** [godaddy/timings-client-py#1]
When following instructions in the readme, there is a line advising to setup custom config.

`
config_file = os.path.join(os.path.abspath(os.path.dirname(__file__)), '', 'my_config.yaml')
PC = Perf(perf.get_config(config_file))
`

with `from timingsclient.perf import Perf`, linter (and run later on) throws an exception:

`
Traceback (most recent call last):
  File "<path to py>/test.py", line 17, in <module>
    PC = Perf(perf.get_config(config_file))
AttributeError: module 'timingsclient.perf' has no attribute 'get_config'
`

Can you please take a look? Or update the readme according to expectations? Thanks!!

Tested on macOS 10.13 w/ python 3.6.3

**Comment by mverkerk-godaddy** [comment]
Good catch! that was some old code ... i updated the example code in the README file. You should be able to follow that. Thx!
