### ISSUE TITLE
ImportError: No module named timingsclient [ Jenkins only ]

### ISSUE THREAD

**Issue by vikramvi** [godaddy/timings-client-py#2]
- I'm trying to do local jenkins setup to run script every hours per instructions from 

https://github.com/softwaresaved/build_and_test_examples/blob/master/jenkins/Shell.md

- `shell file` which I'm planning to run with `jenkins job` is https://github.com/vikramvi/timings-demo/blob/master/py/job.sh

- jenkins job error

code : https://github.com/vikramvi/timings-demo/tree/master/py

```
Building in workspace /home/vingleshwar/Documents/VikramIngleshwar/PerformanceTesting/timings-demo/py
[py] $ /bin/sh -xe /tmp/jenkins1829599534415325144.sh
+ pip install selenium
Collecting selenium
  Downloading selenium-3.8.0-py2.py3-none-any.whl (941kB)
Installing collected packages: selenium
Successfully installed selenium
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
+ ./job.sh 20
Attempt Number : 1
Smava Home Page
Traceback (most recent call last):
  File "smava/chrome_perf_smavaHomePage.py", line 4, in <module>
    from timingsclient import Perf
ImportError: No module named timingsclient
check24 Home Page
Traceback (most recent call last):
  File "check24/chrome_perf_check24HomePage.py", line 4, in <module>
    from timingsclient import Perf
ImportError: No module named timingsclient
geld Home Page
Traceback (most recent call last):
  File "geld/chrome_perf_geldHomePage.py", line 4, in <module>
    from timingsclient import Perf
ImportError: No module named timingsclient
finanzcheck Home Page
Traceback (most recent call last):
  File "finanzcheck/chrome_perf_finanzcheckHomePage.py", line 4, in <module>
    from timingsclient import Perf
```

I've `timings library` already installed with `timings-docker setup` 
-  it works fine when ran outside jenkins setup  [PASS]
- but jenkins is unable to access this setup, please clarify [ FAIL ]

**Comment by mverkerk-godaddy** [comment]
Looks like you need to run `pip install timingsclient` on the Jenkins slave - the same way you're running `pip install selenium` ... this is the client side and is therefore not related to the `timings-docker` install which is the API side. Hope that helps?

**Comment by vikramvi** [comment]
Thanks for clarification, closing as could get setup working
